# Generated by Django 5.2.5 on 2025-08-16 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('classical', 'Classical'), ('hiphop', 'Hip-Hop'), ('jazz', 'Jazz'), ('folk', 'Folk'), ('blues', 'Blues'), ('rnb', 'R&B'), ('electronic', 'Electronic'), ('metal', 'Metal'), ('country', 'Country'), ('reggae', 'Reggae')], max_length=32)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('pa', 'Punjabi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam')], default='en', max_length=8)),
                ('image', models.ImageField(upload_to='song_images/')),
                ('description', models.TextField(blank=True)),
                ('audio', models.FileField(upload_to='songs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(related_name='songs', to='songs.artist')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
