# Generated by Django 5.2.5 on 2025-08-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(related_name='songs', to='songs.genretag'),
        ),
    ]
