# Generated by Django 5.2.5 on 2025-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_genretag_remove_song_genre_alter_song_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.DeleteModel(
            name='GenreTag',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('classical', 'Classical'), ('hiphop', 'Hip-Hop'), ('jazz', 'Jazz'), ('folk', 'Folk'), ('blues', 'Blues'), ('rnb', 'R&B'), ('electronic', 'Electronic'), ('metal', 'Metal'), ('country', 'Country'), ('reggae', 'Reggae')], default='pop', max_length=32),
        ),
    ]
